name: Playwright Tests

on:
  push:
    branches: [main]   # Runs on every push to the main branch
  pull_request:
    branches: [main]   # Runs on every PR to the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Runs on Linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Checks out your code from GitHub

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Use the latest stable Node.js version

      - name: Install dependencies
        run: npm install  # Installs Playwright and other dependencies

      - name: Install Playwright browsers
        run: npx playwright install --with-deps  # Ensures browsers are installed

      - name: Run Playwright tests
        run: npx playwright test  # Runs all Playwright tests

      - name: Upload Playwright report
        if: always()  # Always run this step to upload the test report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7  # Keeps reports for 7 days
